---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: chopper
description: This is my personal OS image.
alt-tags:
  - secureblue-nvidia-open-hyprland

base-image: ghcr.io/secureblue/wayblue-hyprland-nvidia-open-hardened
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - rechunk-fix.sh
      - nvidia-powerlimit.sh
      - opentablet.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
    install:
      # Hypr
      #- hyprland-git
      - hyprlock
      - hypridle
      - hyprpicker
      - hyprshot
      - hyprcursor
      - xcur2png
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - hyprpaper
      - swww

      # Bar
      - waybar
      - SwayNotificationCenter

      # launchers
      - rofi-wayland

      # file manager
      - thunar
      - thunar-archive-plugin
      - thunar-volman

      # polkit
      - xfce-polkit

      # terminal
      - foot

      # Containers
      - podman
      - podman-compose
      - buildah
      - distrobox

      # cli tools
      - android-tools
      - zsh
      - pipx
      - fastfetch
      - btop
      - neovim
      - bat
      - eza
      - ncdu
      - fd-find
      - gh
      - glab
      - tealdeer
      - ugrep
      - yq
      - tmux
      - zoxide
      - ShellCheck
      - starship
      - wget
      - aria2
      - libsixel
      - libsixel-utils

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system: {}
    user:
      install:
        - io.github.zen_browser.zen
        - com.github.tchx84.Flatseal
        - org.kde.krita
        - dev.vencord.Vesktop
        - com.vscodium.codium
        - com.github.wwmm.easyeffects

  - type: chezmoi
    repository: "https://github.com/CarrionAnimus/dotfiles"
    branch: "hyprland"
    all-users: true
    file-conflict-policy: replace

  - type: signing