RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods-nvidia-open:bazzite-42-6.16.4-115.bazzite.fc42.x86_64,src=/rpms,dst=/tmp/akmods-rpms \
  dnf5 -y copr enable ublue-os/staging fedora-42-x86_64 && \
  dnf5 -y install \
      egl-wayland.x86_64 \
      egl-wayland.i686 \
      egl-wayland2.x86_64 \
      egl-wayland2.i686 && \
  curl "https://raw.githubusercontent.com/ublue-os/main/refs/heads/main/build_files/nvidia-install.sh" -o /tmp/nvidia-install.sh && \
      chmod +x /tmp/nvidia-install.sh && \
      IMAGE_NAME="secureblue" KERNEL_VERSION="bazzite-42-6.16.4-115.bazzite.fc42.x86_64" NVIDIA_AKMOD_VERSION="nvidia-open" /tmp/nvidia-install.sh && \
      rm -f /usr/share/vulkan/icd.d/nouveau_icd.*.json && \
      ln -s libnvidia-ml.so.1 /usr/lib64/libnvidia-ml.so && \
  dnf5 -y copr disable ublue-os/staging \
  && dnf5 clean all \
  && rm -rf /tmp/* || true \
  && ostree container commit
