RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods:bazzite-42-6.16.4-115.bazzite.fc42.x86_64,src=/kernel-rpms,dst=/tmp/kernel-rpms \
  dnf5 -y config-manager setopt "*fedora*".exclude="kernel-core-* kernel-modules-* kernel-uki-virt-*" \
  && dnf5 -y remove --no-autoremove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-tools kernel-tools-libs kernel-uki-virt \
  && dnf5 -y install \
    /tmp/kernel-rpms/kernel-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-core-*.rpm \
    /tmp/kernel-rpms/kernel-modules-*.rpm \
    /tmp/kernel-rpms/kernel-tools-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-tools-libs-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-devel-*.rpm \
  && dnf5 versionlock add kernel kernel-devel kernel-devel-matched kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-tools kernel-tools-libs \
  && dnf5 -y copr enable bieszczaders/kernel-cachyos-addons fedora-42-x86_64 \
      && dnf5 -y install scx-scheds \
    && dnf5 -y copr disable bieszczaders/kernel-cachyos-addons \
  && dnf5 clean all \
  && rm -rf /tmp/* || true \
  && ostree container commit
